anguage: node_js
node_js:
  - 12
env:
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/greeting'
before_script:
  - npm install
  - psql -c 'create database  greeting;' -U postgres
  - psql -U postgres -d greeting -a -f greeting.sql
services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4
